{% set name = "cffsubr" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cffsubr-{{ version }}.tar.gz
  sha256: 7745150bdb81679facdd11c1f3b87096c4f4dbd4957e8fcebb88c45687952efb

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
    - cmake
    - scikit-build
  run:
    - fonttools >=4.10.2
    - python

test:
  imports:
    - cffsubr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adobe-type-tools/cffsubr
  summary: Standalone CFF subroutinizer based on the AFDKO tx tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
